spring.application.name=horario

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
 
 # permitir que o banco de dados possa criar tabelas automaticamente
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
